# Generated by Django 4.2.21 on 2025-05-26 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
